function seedUsers(req, res) {
    const users =[
        {username: "johnsonandjohnson", password: "soap123", gender: "male", age: 25},
        {username: "ajay", password: "music123", gender: "male", age: 25 },
        {username: "jenna", password: "jenna123", gender: "female", age: 14 },
        {username: "kylie", password: "kylie123", gender: "female", age: 45},
        {username: "Demo_User", password: "password123", gender: "female", age: 32 },
        {username: "josh", password: "bikes123", gender: "male", age: 25 },
        {username: "haseeb", password: "poker123", gender: "male", age: 16 },
        {username: "joe", password: "password123", gender: "male", age: 59 },
        {username: "jimmy", password: "pokemon123", gender: "male", age: 12 },
        {username: "mike", password: "canada123", gender: "male", age: 26 },
        {username: "yinglan", password: "math123", gender: "female", age: 25},
        {username: "georgecarman", password: "cars123", gender: "male", age: 65 },
        {username: "raphael", password: "ciggys123", gender: "male", age: 15 },
        {username: "joanna", password: "cats123", gender: "female", age: 39 }
    ];

    for (user of users) {
        var newUser = new User(user);
        newUser.save();
    }

    res.send('User database seeded!')
}

function seedQuestions(req, res) {
    const questions = [
        {user: 1, option1: "Fight 100 duck-sized horses", option2: "Fight 1 duck-sized horse", questionType: "wyr", body: "", upvote: 4, downvote: 1},
        {user: 2, option1: "Work your dream job with a 4 hour commute", option2: "Work a satisfying job with a 10 minute commute", questionType: "wyr", body: "", upvote: 5, downvote: 0},
        {user: 3, option1: "Give up cheese", option2: "Give up chocolate", questionType: "wyr", body: "", upvote: 10, downvote: 4 },
        {user: 4, option1: "Control animals with your mind", option2: "Control humans with your mind", questionType: "wyr", body: "", upvote: 2, downvote: 2 },
        {user: 5, option1: "All your shirts are 2 sizes too big", option2: "All your shirts are 1 size too small", questionType: "wyr", body: "", upvote: 4, downvote: 1 },
        {user: 6, option1: "Cheeto dust on your fingers for 2 years", option2: "Wet socks for a year", questionType: "wyr", body: "", upvote: 4, downvote: 2 },
        {user: 7, option1: "Be a master at every isnstrument", option2: "Be fluent in every language", questionType: "wyr", body: "", upvote: 4, downvote: 0 },
        {user: 1, option1: "Have super sensitive hearing", option2: "Have super sensitive taste", questionType: "wyr", body: "", upvote: 4, downvote: 4 },
        {user: 2, option1: "Be able to fly", option2: "Be able to become invisible", questionType: "wyr", body: "", upvote: 16, downvote: 1 },
        {user: 5, option1: "Win $10,000", option2: "Let your best friend with $100,000", questionType: "wyr", body: "", upvote: 5, downvote: 1 },
        {user: 6, option1: "Redflag", option2: "Dealbraker", questionType: "rfdb", body: "Has 9 dogs", upvote: 4, downvote: 2 },
        {user: 7, option1: "Redflag", option2: "Dealbraker", questionType: "rfdb", body: "Has a face tattoo", upvote: 15, downvote: 0 },
        {user: 1, option1: "Redflag", option2: "Dealbraker", questionType: "rfdb", body: "Has been in prison", upvote: 3, downvote: 4 },
        {user: 2, option1: "Redflag", option2: "Dealbraker", questionType: "rfdb", body: "Never breaks eye contact", upvote: 0, downvote: 1 },
        {user: 5, option1: "Redflag", option2: "Dealbraker", questionType: "rfdb", body: "Does not live in a place for > 2 years", upvote: 1, downvote: 1 }
    ];

    for (question of questions) {
        var newQuestion = new Question(question);
        newQuestion.save();
    }

    res.send('Question database seeded!')
}

function seedAnswers(req, res){
    const answers =[
        {user: {_id: 1, age: 25, gender: 'male',}, question: 1, answer: "a"},
        {user: { _id: 1, age: 25, gender: 'male', }, question: 2, answer: "b"},
        { user: { _id: 1, age: 25, gender: 'male', }, question: 3, answer: "b" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 4, answer: "a" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 5, answer: "b" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 6, answer: "a" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 7, answer: "b" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 8, answer: "a" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 9, answer: "b" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 10, answer: "a" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 11, answer: "b" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 12, answer: "a" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 13, answer: "b" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 14, answer: "a" },
        { user: { _id: 1, age: 25, gender: 'male', }, question: 15, answer: "b" },

        { user: { _id: 2, age: 25, gender: 'male', }, question: 1, answer: "b" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 2, answer: "a" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 3, answer: "b" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 4, answer: "b" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 5, answer: "b" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 6, answer: "b" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 7, answer: "b" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 8, answer: "a" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 9, answer: "a" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 10, answer: "a" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 11, answer: "b" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 12, answer: "a" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 13, answer: "a" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 14, answer: "a" },
        { user: { _id: 2, age: 25, gender: 'male', }, question: 15, answer: "b" },

        { user: { _id: 3, age: 14, gender: 'female', }, question: 1, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 2, answer: "b" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 3, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 4, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 5, answer: "b" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 6, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 7, answer: "b" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 8, answer: "b" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 9, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 10, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 11, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 12, answer: "a" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 13, answer: "b" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 14, answer: "b" },
        { user: { _id: 3, age: 14, gender: 'female', }, question: 15, answer: "a" },


        { user: { _id: 4, age: 45, gender: 'female', }, question: 1, answer: "b" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 2, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 3, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 4, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 5, answer: "b" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 6, answer: "b" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 7, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 8, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 9, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 10, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 11, answer: "b" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 12, answer: "b" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 13, answer: "b" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 14, answer: "a" },
        { user: { _id: 4, age: 45, gender: 'female', }, question: 15, answer: "a" },

        { user: { _id: 5, age: 32, gender: 'female', }, question: 1, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 2, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 3, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 4, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 5, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 6, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 7, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 8, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 9, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 10, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 11, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 12, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 13, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 14, answer: "a" },
        { user: { _id: 5, age: 32, gender: 'female', }, question: 15, answer: "a" },

        { user: { _id: 6, age: 25, gender: 'male', }, question: 1, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 2, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 3, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 4, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 5, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 6, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 7, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 8, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 9, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 10, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 11, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 12, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 13, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 14, answer: "b" },
        { user: { _id: 6, age: 25, gender: 'male', }, question: 15, answer: "b" },

        { user: { _id: 7, age: 16, gender: 'male', }, question: 1, answer: "a" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 2, answer: "b" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 3, answer: "a" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 4, answer: "b" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 5, answer: "a" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 6, answer: "b" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 7, answer: "a" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 8, answer: "b" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 9, answer: "a" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 10, answer: "b" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 11, answer: "a" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 12, answer: "b" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 13, answer: "a" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 14, answer: "b" },
        { user: { _id: 7, age: 16, gender: 'male', }, question: 15, answer: "a" },

        { user: { _id: 8, age: 59, gender: 'male', }, question: 1, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 2, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 3, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 4, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 5, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 6, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 7, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 8, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 9, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 10, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 11, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 12, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 13, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 14, answer: "b" },
        { user: { _id: 8, age: 59, gender: 'male', }, question: 15, answer: "b" },

        { user: { _id: 9, age: 12, gender: 'male', }, question: 1, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 2, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 3, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 4, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 5, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 6, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 7, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 8, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 9, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 10, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 11, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 12, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 13, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 14, answer: "a" },
        { user: { _id: 9, age: 12, gender: 'male', }, question: 15, answer: "a" },
        
        { user: { _id: 10, age: 26, gender: 'male', }, question: 1, answer: "b" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 2, answer: "a" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 3, answer: "b" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 4, answer: "a" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 5, answer: "b" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 6, answer: "a" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 7, answer: "b" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 8, answer: "a" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 9, answer: "b" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 10, answer: "a" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 11, answer: "b" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 12, answer: "a" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 13, answer: "b" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 14, answer: "a" },
        { user: { _id: 10, age: 26, gender: 'male', }, question: 15, answer: "b" },

        { user: { _id: 11, age: 25, gender: 'female', }, question: 1, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 2, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 3, answer: "b" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 4, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 5, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 6, answer: "b" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 7, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 8, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 9, answer: "b" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 10, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 11, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 12, answer: "b" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 13, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 14, answer: "a" },
        { user: { _id: 11, age: 25, gender: 'female', }, question: 15, answer: "b" },

        { user: { _id: 12, age: 65, gender: 'male', }, question: 1, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 2, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 3, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 4, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 5, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 6, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 7, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 8, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 9, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 10, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 11, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 12, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 13, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 14, answer: "a" },
        { user: { _id: 12, age: 65, gender: 'male', }, question: 15, answer: "a" },

        { user: { _id: 13, age: 15, gender: 'male', }, question: 1, answer: "a" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 2, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 3, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 4, answer: "a" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 5, answer: "a" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 6, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 7, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 8, answer: "a" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 9, answer: "a" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 10, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 11, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 12, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 13, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 14, answer: "b" },
        { user: { _id: 13, age: 15, gender: 'male', }, question: 15, answer: "a" },

        { user: { _id: 14, age: 39, gender: 'male', }, question: 1, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 2, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 3, answer: "b" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 4, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 5, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 6, answer: "b" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 7, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 8, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 9, answer: "b" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 10, answer: "b" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 11, answer: "b" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 12, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 13, answer: "a" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 14, answer: "b" },
        { user: { _id: 14, age: 39, gender: 'male', }, question: 15, answer: "a" }
    ]

    for (answer of answers) {
        var newAnswer = new Answer(answer);
        newAnswer.save();
    }

    res.send('Answer database seeded!')
}

seedUsers();
seedQuestions();
seedAnswers(); 